### ISSUE TITLE
Index organisation and project metadata in the Knowledge Graph

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#736] opened 2019-08-28 06:33 UTC
I think it could be extremely useful to have organisation and project data in the knowledge graph in order to achieve things like:

```sparql
prefix nxv: <https://bluebrain.github.io/nexus/vocabulary/>

SELECT * WHERE {
  ?s rdf:type nxv:View ;
     nxv:project / rdfs:label ?projectLabel
}
```

When writing client applications, we very often need to know the organisation and project label (if we want to display it in a breadcrumb for example, or even in order to build the API call URL, etc...)

Right now we have to parse the `_self` URL to get those values but of the metadata was in the KG we'd simply be able to query it!

**Comment by umbreak** [comment] 2019-09-27 13:02
The project information is present in the triple store in the predicate `nxv:project`. The stored value is in the form `myorg/myproject`.

Certainly the organization information could be added too.

**Comment by bogdanromanx** [comment] 2021-02-15 16:03
Duplicate of #2038 .

**Closed by bogdanromanx** 2021-02-15 16:03 UTC
Labels: :zap: team:backend, 🌈 enhancement
