### ISSUE TITLE
Unable to create resources under schema

### ISSUE THREAD

**Issue by ehsanmaag** [BlueBrain/nexus#448] opened 2019-02-13 22:04 UTC
I have a simple schema created on sandbox:

```
{
    "@context": [
        "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest10",
        "https://bluebrain.github.io/nexus/contexts/shacl-20170720.json",
        "https://bluebrain.github.io/nexus/contexts/resource.json"
    ],
    "@id": "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtestb2",
    "@type": "Schema",
    "shapes": [
        "medred:titleShape",
        {
            "@id": "medred:Question",
            "@type": "NodeShape",
            "comment": {
                "@language": "en",
                "@value": "A Question is an Instrument item consisting of an inquiry or query to a subject"
            },
            "label": {
                "@language": "en",
                "@value": "Question"
            },
            "property": [
                {
                    "@id": "medred:titleShape",
                    "@type": "PropertyShape",
                    "minCount": 1,
                    "path": "terms:title",
                    "sh:dataType": "xsd:string"
                },
                "medred:hasOutputVarShape"
            ],
            "targetClass": "medred:Question"
        },
        {
            "@id": "medred:hasOutputVarShape",
            "@type": "PropertyShape",
            "class": "pplan:Variable",
            "path": "pplan:hasOutputVar"
        }
    ],
    "_self": "https://nexus-sandbox.io/v1/schemas/kcnitest/redcap/base:medredtestb2",
    "_constrainedBy": "nxs:shacl-20170720.ttl",
    "_project": "https://nexus-sandbox.io/v1/projects/kcnitest/redcap",
    "_rev": 1,
    "_deprecated": false,
    "_createdAt": "2019-02-13T21:45:44.889Z",
    "_createdBy": "https://nexus-sandbox.io/v1/realms/github/users/ehsanmaag",
    "_updatedAt": "2019-02-13T21:45:44.889Z",
    "_updatedBy": "https://nexus-sandbox.io/v1/realms/github/users/ehsanmaag"
}
```

and I am trying to create an instance based on the schema:

```
{ '@type': 'medred:Question', 'identifier': 'phq9_1', 'title': '1. Little interest or pleasure in doing things', '@context': ['https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest10'] }
```

Any call to PUT or POST methods using Postman or Nexus-SDK fails with error: "405 Client Error: Method Not Allowed"
Request URL that nexussdk uses:
https://nexus-sandbox.io/v1/resources/kcnitest/redcap/medredtest3/phq9_1

The same instance gets created without schema ("_").

**Comment by MFSY** [comment] 2019-02-16 19:14
Hi,
It seems that the issue comes from different schema identifiers (**medredtestb2 vs medredtest3**):

* The schema is identified by **medredtestb2** (which expands to https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtestb2) while the schema you're targeting in your request URL (when creating an instance) is identified by **medredtest3** (which expands to https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtest3). 
I suggest you align the targeted schema identifier with an actual existing schema identifier and try again.


* If the issue is about different schemas identifiers then a **405 Method Not Allowed** message does definitely not help debug. I suggest you open an issue on that.


Hope this help.

**Comment by ehsanmaag** [comment] 2019-02-19 16:27
Sorry that was a copying mistake on my part ...
Using identifier "medredtestb2" still fails in Postman.

The request below returns the correct schema:
```
GET /v1/resources/kcnitest/redcap/_/medredtestb2 HTTP/1.1
Host: nexus-sandbox.io
```

The request below returns the correct context resource:
```
GET /v1/resources/kcnitest/redcap/_/medredcontexttest10 HTTP/1.1
Host: nexus-sandbox.io
```

The request below:
```
PUT /v1/resources/kcnitest/redcap/medredtestb2/phq9_1 HTTP/1.1
Host: nexus-sandbox.io
Content-Type: application/json
{ 
	"@type": "medred:Question", 
	"identifier": "phq9_1", 
	"title": "Little interest in doing things", 
	"@context": [
		"https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest10"
		] 
}
```
returns:
```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "HttpMethodNotAllowed",
    "reason": "HTTP method not allowed, supported methods: 'GET', 'POST'."
}
```

The request below:
```
POST /v1/resources/kcnitest/redcap/medredtestb2 HTTP/1.1
Host: nexus-sandbox.io
Content-Type: application/json
{ 
	"@type": "medred:Question", 
	"@id": "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/medredtestb2/phq9_1",
	"identifier": "phq9_1", 
	"title": "Little interest in doing things", 
	"@context": [
		"https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest10"
		] 
}
```
returns:
```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "NotFound",
    "reason": "The requested resource could not be found."
}
```

kcnitest/redcap Project Base URL: https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/
kcnitest/redcap Project has no API mapping.

**Comment by ehsanmaag** [comment] 2019-02-19 17:49
Sorry that was a mistake on my part, I created a new schema and tested:
Using identifier "medredtestb8" instead, and it still fails in Postman.

The request below returns the correct schema:
```
GET /v1/schemas/kcnitest/redcap/medredtestb8 HTTP/1.1
Host: nexus-sandbox.io
```

The request below returns the correct context resource:
```
GET /v1/resources/kcnitest/redcap/_/medredcontexttest12 HTTP/1.1
Host: nexus-sandbox.io
```

The request below:
```
PUT /v1/resources/kcnitest/redcap/medredtestb8/phq9_1 HTTP/1.1
Host: nexus-sandbox.io
Content-Type: application/json
{ 
	"@type": "medred:Question", 
	"identifier": "phq9_1", 
	"title": "Little interest in doing things", 
	"@context": [
		"https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest12"
		] 
}
```
returns:
```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "HttpMethodNotAllowed",
    "reason": "HTTP method not allowed, supported methods: 'GET', 'POST'."
}
```

The request below:
```
POST /v1/resources/kcnitest/redcap/medredtestb8 HTTP/1.1
Host: nexus-sandbox.io
Content-Type: application/json
{ 
	"@type": "medred:Question",
	"identifier": "phq9_1", 
	"title": "Little interest in doing things", 
	"@context": [
		"https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest12"
		] 
}
```
returns:
```
{
    "@context": "https://bluebrain.github.io/nexus/contexts/error.json",
    "@type": "NotFound",
    "reason": "The requested resource could not be found."
}
```

kcnitest/redcap Project Base URL: https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/
kcnitest/redcap Project has no API mapping.

**Comment by umbreak** [comment] 2019-02-20 09:14
I understand that now the issue is solved. Thanks for the feedback. I proceed to closing it.

**Comment by ehsanmaag** [comment] 2019-02-20 15:17
> I understand that now the issue is solved. Thanks for the feedback. I proceed to closing it.

Unfortunately the issue has not been resolved. I am using a uniform ID for the schema while I get the errors.

**Comment by MFSY** [comment] 2019-02-23 15:20
The error is caused by the schema not being found in both the PUT and POST requests you mentioned.

A schema is always identified by an http based URI in Nexus. Let first get the schema identifier.

Run a:
```
GET /v1/schemas/kcnitest/redcap/medredtestb8 
```
and look at the @id key in the payload you get from Nexus. That's your schema identifier (**not medredtestb8**). As you can see, the schema identifier is a  concatenation of the value of the **base** key in the 'redcap' project configuration and **medredtestb8**. To get the project configuration and check yourself, run: 

```
GET /v1/projects/kcnitest/redcap
```

Now to create resources using the schema identifier, you have two options.

1. Refer to the schema by its http URI: the schema URI should be url encoded in this case (let call it {schema_url_encoded_uri}): 

```
PUT /v1/resources/kcnitest/redcap/{schema_url_encoded_uri}/phq9_1

OR 

POST /v1/resources/kcnitest/redcap/{schema_url_encoded_uri} 
```

2. Refer to the schema by CURIE (in the form prefix:namespace) or alias (for example medredtestb8)

```
PUT /v1/resources/kcnitest/redcap/medredtestb8/phq9_1

OR 

POST /v1/resources/kcnitest/redcap/medredtestb8
```


In this case both CURIEs or aliases (medredtestb8) should be expanded to a fully qualified URI. The expansion happened through the project configuration. Did you define 'medredtestb8' as a prefix in the [apiMappings](https://bluebrain.github.io/nexus/docs/api/admin/admin-projects-api.html#api-mappings
) array of the 'redcap' project configuration ? If not and you still want to use 'medredtestb8' as alias of your schema then update the project by adding the following:

```
"apiMappings": [
   {
      "prefix": "medredtestb8",
      "namespace": "the_schema_http_uri"
    }
  ]

```

**Comment by ehsanmaag** [comment] 2019-02-25 17:28
Thanks for the response; I went through the steps described above still with no success:

> first get the schema identifier.

I get this @id from the schema payload:
`"@id": "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtestb8"
`
> run:
> ```
> GET /v1/projects/kcnitest/redcap
> ```

I do have an API mapping for medredtestb8, and base url look like this:
```
"base": "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/",
    "apiMappings": [
        {
            "prefix": "medredtestb8",
            "namespace": "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtestb8"
        }
    ], ...
```

I will be testing this resource:
`obj = {'@type': 'medred:Question', 'identifier': 'phq9_1_5', 'title': 'Little interest in doing things', '@context': ['https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredcontexttest12']}`

- Option 1, using the full schema id,
command: 
```
instance = nexus.resources.create(org_label = "kcnitest", 
                                   project_label = "redcap", 
                                   data = json.dumps(obj),
                                   schema_id = "https://nexus-sandbox.io/v1/resources/kcnitest/redcap/_/medredtestb8",
                                   resource_id = None)
```
output:
```
~\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nexussdk\resources.py in create(org_label, project_label, data, schema_id, resource_id)
    107 
    108     if resource_id is None:
--> 109         return http_post(path, data, use_base=True)
    110     else:
    111         resource_id = url_encode(resource_id)
~\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nexussdk\utils\http.py in http_post(path, body, data_type, use_base, **kwargs)
    142         response = requests.post(full_url, headers=header, files=body, params=kwargs)
    143 
--> 144     response.raise_for_status()
    145     return decode_json_ordered(response.text)
    146 
~\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):
HTTPError: 400 Client Error: Bad Request for url: https://nexus-sandbox.io/v1/resources/kcnitest/redcap/https%3A%2F%2Fnexus-sandbox.io%2Fv1%2Fresources%2Fkcnitest%2Fredcap%2F_%2Fmedredtestb8
```

- Option 1, using relative schema id,
command: 
```
instance = nexus.resources.create(org_label = "kcnitest", 
                                   project_label = "redcap", 
                                   data = json.dumps(obj),
                                   schema_id = "/v1/resources/kcnitest/redcap/_/medredtestb8",
                                   resource_id = None)
```
output:
```
...
HTTPError: 404 Client Error: Not Found for url: https://nexus-sandbox.io/v1/resources/kcnitest/redcap/%2Fv1%2Fresources%2Fkcnitest%2Fredcap%2F_%2Fmedredtestb8
```

- Option 2, using schema alias (project contains an API mapping):
command:
```
instance = nexus.resources.create(org_label = "kcnitest", 
                                   project_label = "redcap", 
                                   data = json.dumps(obj),
                                   schema_id = "medredtestb8",
                                   resource_id = None)
```
output:
```
...
HTTPError: 400 Client Error: Bad Request for url: https://nexus-sandbox.io/v1/resources/kcnitest/redcap/medredtestb8
```

**Comment by ehsanmaag** [comment] 2019-02-26 20:55
I am going to close this issue since the error was resolved following the recent Nexus update. 
HTTP calls successfully complete, however Nexus-sdk calls still produce the same error.

**Closed** 2019-02-26 20:56 UTC
Labels: bug, question
