### ISSUE TITLE
BBP staging nexus query endpoint after number of queries goes down

### ISSUE THREAD

**Issue by genric** [BlueBrain/nexus#62] opened 2018-08-07 12:02 UTC
Hi,
    When trying to execute number of consecutive queries staging gives 500. I tried it several times and it always does it. Let me know if you want me to reproduce it. I would appreciate if somebody looks at this. Thanks.

**Comment by bogdanromanx** [comment] 2018-08-07 12:17
How many queries are you executing? Are they sequential or done in parallel? Are you experiencing a long delay in getting the 500 error? Does the issue occur when doing just listings or queries that apply filters on the graph? What is the response body that you get when an error occurs?

Most likely it's caused by the underlying network issues (we're seeing some failures in our trace reporting), but please answer the above to confirm.

**Comment by genric** [comment] 2018-08-08 08:10
As I understood from our chat with @wwajerowicz in gitter, he will have a look at this.

**Comment by genric** [comment] 2018-08-08 08:52
Hi,
    I'm executing around ~ 200 queries. The failure can happen at some random number of queries around 200.
    They are all run in sequence.
    The failure happens when accessing entity by full id url from the query result set or on the query itself. I don't know what are the delays here. But if absolutely required I could measure them.
    Response is:
```
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bbp-nexus.epfl.ch/staging/v0/queries/dc0a67d4-80d2-4587-8da7-92b0ac121a5b?from=0&size=10

{
  "@context":"https://bbp-nexus.epfl.ch/staging/v0/contexts/nexus/core/error/v0.1.0",
  "code":"DownstreamServiceError",
  "message":"Tcp command [Connect(iam.bbp-nexus-staging.svc.cluster.local:80,None,List(),Some(10 seconds),true)] failed because of Connection refused"
}
```

**Comment by umbreak** [comment] 2018-08-08 09:41
We are changing some parameters on the deployment configuration for `iam` (twicking the Xmx parameter) and then we will perform some tests against IAM to figure out if this change fixes the issue.

**Comment by christian-oreilly** [comment] 2018-08-15 10:27
Any ETA on this task? It is currently marked as blocking one of our Nexus integration task in the Thalamus meeting.

**Comment by umbreak** [comment] 2018-08-24 08:50
I close this ticket. So far it seems to work. Let's re-open it if the issue is persistent.

**Closed by umbreak** 2018-08-24 08:50 UTC
