### ISSUE TITLE
Preview of images does not work in Fusion

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3013] opened 2022-01-17 06:45 UTC
**Describe the bug**

The preview of images in the resource of type "PlotCollection" is not working. Example link:

https://staging.nexus.ocp.bbp.epfl.ch/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F5bf44b5a-c188-4a39-b1a3-db81e327e4fe

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to https://staging.nexus.ocp.bbp.epfl.ch/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F5bf44b5a-c188-4a39-b1a3-db81e327e4fe
2. Images cannot be seen

**Expected behavior**
I expect to see a preview of the 4 images.

**Screenshots**
![Screenshot 2022-01-14 at 13 15 37](https://user-images.githubusercontent.com/12729291/149720517-2b701739-ce31-4c52-9b0e-6882f9a895fa.png)

**Comment by samuel-kerrien** [comment] 2022-03-01 09:44
This issue is fixed in #2893.

**Comment by samuel-kerrien** [comment] 2022-03-09 12:43
Duplicate of #2893

**Closed** 2022-03-29 09:07 UTC
Labels: bug, fusion
