### ISSUE TITLE
Search bar behaviour improvements

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2731] opened 2021-08-27 08:14 UTC
Acceptance Criteria (see attached comments for details and videos of the problems):

- [x] The search bar displays the following text: "Search or jump to..."
- [ ] Upon pressing `/`(or clicking on it) the search bar will be focused, the contents of the search bar will be selected such that typing will replace the current contents https://github.com/BlueBrain/nexus/issues/2609#issuecomment-906995492
- [x]  The search bar content should match the query from Search (if any), see screenshot below (we searched for `sscx` but the search bar shows the latest searched project instead of `sscx`)
- [ ] When the user selected "Search nexus" in the dropdown, it should query the search endpoint and not send the user to the project page (even if it is the name of the project) https://github.com/BlueBrain/nexus/issues/2610#issuecomment-907015720
- [x]  The dropdown items to jump to project should be labeled "Jump to Project", i.e. capitalize Jump and Project to match the style of "Search Nexus"
- [x]  After typing a query in the search bar, if you hit enter, it should search immediately (it should pick the first option in the dropdown).

![image](https://user-images.githubusercontent.com/11705901/131096248-50fab8cd-b75e-4679-acc8-df7c5e4e0cd7.png)

Please re-test the acceptance criteria of the following tickets once this is fixed:

- https://github.com/BlueBrain/nexus/issues/2609
- https://github.com/BlueBrain/nexus/issues/2610

**Comment by Stafeeva** [comment] 2021-09-16 09:24
The remaining bugs are caused by antd limitations/design:

- Upon pressing /(or clicking on it) the search bar will be focused, the contents of the search bar will be selected such that typing will replace the current contents:

the content of the Search bar is not selected properly, because <Input /> is wrapped in <Autocomplete />
and doesn't have its own value or defaultValue to highlight

- When the user selected "Search nexus" in the dropdown, it should query the search endpoint and not send the user to the project page (even if it is the name of the project)

This doesn't work properly with the project names like 'test/sscx'. This is a tricky one, because in the list of dropdown options, if a user searches for a project, there will be rendered two options with the same value: one as 'search nexus' another as 'go to project', and selecting an option will return an option by value, not a key or anything else we might try to assign to distinguish them, and will return a wrong one unfortunately :(

**Closed** 2021-09-28 11:11 UTC
Labels: bug, enhancement, fusion
