### ISSUE TITLE
Resource Instance Relationship Visualization

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#830] opened 2019-11-07 09:35 UTC
AS A technical user
I WANT TO be able to see the relationships between specific resource instances
SO THAT I CAN understand how they're related without keeping that data in my head
AND SO THAT I CAN navigate to their linked resource instances

- [ ] Navigate to Graph View  #825 
- [ ] Resource As Nodes #827 
- [ ] Expand nodes in the graph #828
- [ ] Navigate to other resources in the graph  #829
- [ ] Persist the graph #826

**Comment by julienmachon** [comment] 2019-11-13 07:37
Duplicate of #820

**Closed by julienmachon** 2019-11-13 07:37 UTC
Labels: epic, nexus-web
