### ISSUE TITLE
Persist the graph

### ISSUE THREAD

**Issue by Stafeeva** [BlueBrain/nexus#826] opened 2019-11-07 09:15 UTC
Part of #820

AS A technical user
I WANT TO see all the resources in the same view which I have expanded
SO THAT I CAN see their relationships in one view

GIVEN that I have expanded the nodes of more relationships
WHEN I expand yet more nodes
THEN I get to have them all displayed in one screen

**Comment by julienmachon** [comment] 2019-11-13 09:48
duplicate of #828

**Closed by julienmachon** 2019-11-13 09:48 UTC
Labels: frontend, nexus-web, story
