### ISSUE TITLE
Revision list spanning outside of viewport when rev list is long, when viewing a resource in project view

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/nexus#4667] opened 2024-01-17 08:57 UTC
**Describe the bug**
Resources with lots of revisions have the revision list span outside of the screen, and no scrolling is possible to access the top ones.

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Open a resource with a lot of revisions, ex: https://bbp.epfl.ch/nexus/web/bbp-external/seu/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fneuronmorphologies%2Fb10b9445-0e4b-4165-be0b-852c7e925717

**Expected behavior**
All revisions can be accessed (maybe revisions show up below the revision selection) 

**Screenshots**
![Screenshot 2024-01-17 at 09 55 57](https://github.com/BlueBrain/nexus/assets/24302104/c7f98fdc-a431-4d10-a6ff-d3ebf1358b92)

**Comment by Dinika** [comment] 2024-01-17 10:59
Duplicate of [#4262](https://app.zenhub.com/workspaces/blue-brain-nexus-60ace035034cae00105c9307/issues/gh/bluebrain/nexus/4262)

**Closed by Dinika** 2024-01-17 10:59 UTC
Labels: bug, fusion
