### ISSUE TITLE
Error when trying to download Files from Data Cart

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3335] opened 2022-06-03 09:41 UTC
**Describe the bug**

I added two items to the Data Cart, and when I hover over "Download" and click on "Files" I get an error "Download Failed".

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to 'Search'
2. Select some items, add them to the cart
3.Open Cart and try to download

**Expected behavior**
Either to be able to download the files, or if there are no files then this option should not be shown.

**Screenshots**

![Jun-03-2022 11-35-20.gif](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/713fcc02-90cd-4400-a03c-dff0ca3ab051)

**Additional context**
Env: Stage Nexus Fusion v1.8.0-M3-1-g03ab697
User: adietz

**Comment by samuel-kerrien** [comment] 2022-06-07 11:46
Duplicate of #3238.

**Closed by samuel-kerrien** 2022-06-07 11:46 UTC
Labels: bug, fusion
