### ISSUE TITLE
Project Resources Shape Visualization

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#832] opened 2019-11-07 09:38 UTC
AS A technical user  
I WANT TO be able to see the shape of types of resources
AND the relationships between types of resources
SO THAT I CAN see how data is related and formatted in a general way across the project

possibly addressed by #821

**Comment by julienmachon** [comment] 2019-11-13 07:36
Duplicate of #821

**Closed by julienmachon** 2019-11-13 07:36 UTC
Labels: epic, nexus-web
